Bump prettier from 3.2.2 to 3.2.3 (#161)
Bumps [prettier](https://github.com/prettier/prettier) from 3.2.2 to 3.2.3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/prettier/prettier/releases">prettier's releases</a>.</em></p>
<blockquote>
<h2>3.2.3</h2>
<ul>
<li>Format <code>tsconfig.json</code> file with <code>jsonc</code> parser <a href="https://redirect.github.com/prettier/prettier/issues/15927">#15927</a></li>
</ul>
<p>🔗 <a href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#323">Changelog</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md">prettier's changelog</a>.</em></p>
<blockquote>
<h1>3.2.3</h1>
<p><a href="https://github.com/prettier/prettier/compare/3.2.2...3.2.3">diff</a></p>
<h4>Throw errors for invalid code (<a href="https://redirect.github.com/prettier/prettier/pull/15881">#15881</a> by <a href="https://github.com/fisker"><code>@​fisker</code></a>, <a href="https://github.com/Josh-Cena"><code>@​Josh-Cena</code></a>, <a href="https://github.com/auvred"><code>@​auvred</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="ts"><code>// Input
1++;
<p>// Prettier 3.2.2
1++;</p>
<p>// Prettier 3.2.3
SyntaxError: Invalid left-hand side expression in unary operation (1:1)
&gt; 1 | 1++;
| ^
</code></pre></p>
<!-- raw HTML omitted -->
<pre lang="ts"><code>// Input
try {} catch (error = 1){}

// Prettier 3.2.2
try {
} catch (error) {}

// Prettier 3.2.3
SyntaxError: Catch clause variable cannot have an initializer. (1:23)
&gt; 1 | try {} catch (error = 1){}
    |                       ^
</code></pre>
<h4>Fix parser inference (<a href="https://redirect.github.com/prettier/prettier/pull/15927">#15927</a> by <a href="https://github.com/fisker"><code>@​fisker</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="console"><code>// Prettier 3.2.2
prettier --file-info tsconfig.json
{ &quot;ignored&quot;: false, &quot;inferredParser&quot;: &quot;json&quot; }
<p>// Prettier 3.2.3
prettier --file-info tsconfig.json
{ &quot;ignored&quot;: false, &quot;inferredParser&quot;: &quot;jsonc&quot; }
</code></pre></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/prettier/prettier/commit/42ba4373f47a67a5d50756a76a57b2ce3a5524e5"><code>42ba437</code></a> Release 3.2.3</li>
<li><a href="https://github.com/prettier/prettier/commit/99c873d4219f02f684ec8f3d200abee04e9bbe85"><code>99c873d</code></a> chore(deps): update typescript-eslint to v6.19.0 (<a href="https://redirect.github.com/prettier/prettier/issues/15939">#15939</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/86fd77d9cd183a642f0429c9112fcebf9f9a8365"><code>86fd77d</code></a> chore(deps): update dependency flow-parser to v0.226.0 (<a href="https://redirect.github.com/prettier/prettier/issues/15931">#15931</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/12ab5852fa32888c21e9de2c52d3c6952265457f"><code>12ab585</code></a> chore(deps): update dependency browserslist-to-esbuild to v2.1.1 (<a href="https://redirect.github.com/prettier/prettier/issues/15930">#15930</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/c566c9df08936c1a8e32c61ba5760455ef43b575"><code>c566c9d</code></a> Fix parser inference (<a href="https://redirect.github.com/prettier/prettier/issues/15927">#15927</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/be174056690dd1236c9dc3b4167c811245f8c584"><code>be17405</code></a> Simplify <code>isSimpleCallArgument</code> (<a href="https://redirect.github.com/prettier/prettier/issues/15923">#15923</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/10762eeaa0c5af3bbcd12dddad213746cc8ff08f"><code>10762ee</code></a> Improve keyword detection in <code>TSModuleDeclaration</code> (<a href="https://redirect.github.com/prettier/prettier/issues/15925">#15925</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/70c9c56c67e6c3061187abed571ca43f1a7e0608"><code>70c9c56</code></a> Improve babel parse error message (<a href="https://redirect.github.com/prettier/prettier/issues/15928">#15928</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/1e1942dc46062fc09ef5dfcbe8f57157b32eef69"><code>1e1942d</code></a> Remove outdated babel reasonCode (<a href="https://redirect.github.com/prettier/prettier/issues/15929">#15929</a>)</li>
<li><a href="https://github.com/prettier/prettier/commit/d386ff8f7c36b87482f525620824f7839d540730"><code>d386ff8</code></a> Simplify <code>printBinaryCastExpression</code> (<a href="https://redirect.github.com/prettier/prettier/issues/15932">#15932</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/prettier/prettier/compare/3.2.2...3.2.3">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=prettier&package-manager=npm_and_yarn&previous-version=3.2.2&new-version=3.2.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

You can trigger a rebase of this PR by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this group update PR and stop Dependabot creating any more for the specific dependency's major version (unless you unignore this specific dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this group update PR and stop Dependabot creating any more for the specific dependency's minor version (unless you unignore this specific dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR and stop Dependabot creating any more for the specific dependency (unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will remove the ignore condition of the specified dependency and ignore conditions


</details>